name: Deno CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Deno
      uses: denoland/setup-deno@v1.1.0  # Specify a valid version here
      with:
        deno-version: v1.23.0  # Specify the Deno version you need
